# Generated by Django 6.0.3 on 2026-04-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='domain',
        ),
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, help_text='Application or project deadline. Recommended for industry projects.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='industry_name',
            field=models.CharField(blank=True, help_text='Name of the sponsoring company / industry partner. Required for industry projects.', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('academic', 'Academic'), ('industry', 'Industry')], default='academic', help_text='Academic = internal research project. Industry = company-sponsored project.', max_length=10),
        ),
    ]
