# Generated by Django 6.0.3 on 2026-05-22 10:44

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_domain_project_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.FileField(blank=True, help_text='Detailed project specification document (PDF/DOC, max 20 MB).', null=True, upload_to=projects.models.project_upload_path),
        ),
    ]
