# Generated by Django 6.0.3 on 2026-04-01 18:16

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Cover image (JPG/PNG, max 5 MB).', null=True, upload_to=blog.models.blog_image_upload_path)),
                ('category', models.CharField(blank=True, help_text='e.g. Research, AI, Fellowship', max_length=100)),
                ('external_link', models.URLField(blank=True, help_text='Optional external article or reference URL.')),
                ('author_name', models.CharField(help_text='Displayed publicly on the blog post.', max_length=150)),
                ('author_email', models.EmailField(help_text='Stored privately — never shown publicly.', max_length=254)),
                ('author_contact', models.CharField(help_text='Stored privately — never shown publicly.', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'ordering': ['-created_at'],
            },
        ),
    ]
