# Generated by Django 6.0.3 on 2026-04-01 10:39

import proposals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional resume, transcript, or recommendation letter (PDF/DOC, max 5 MB).', null=True, upload_to=proposals.models.proposal_upload_path),
        ),
    ]
