# Generated by Django 6.0.3 on 2026-04-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_alter_proposal_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='applicant_contact',
            field=models.CharField(blank=True, help_text='Phone number.', max_length=20),
        ),
        migrations.AddField(
            model_name='proposal',
            name='applicant_department',
            field=models.CharField(blank=True, help_text='Department / branch.', max_length=150),
        ),
        migrations.AddField(
            model_name='proposal',
            name='applicant_email',
            field=models.EmailField(blank=True, help_text='Contact email.', max_length=254),
        ),
        migrations.AddField(
            model_name='proposal',
            name='applicant_name',
            field=models.CharField(blank=True, help_text='Full name of the applicant.', max_length=150),
        ),
        migrations.AddField(
            model_name='proposal',
            name='applicant_roll_no',
            field=models.CharField(blank=True, help_text='University roll number.', max_length=50),
        ),
        migrations.AddField(
            model_name='proposal',
            name='applicant_year',
            field=models.IntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], help_text='Current year of study.', null=True),
        ),
    ]
