# Generated by Django 6.0.3 on 2026-05-22 10:02

import proposals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposal_applicant_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='attachment',
            field=models.FileField(help_text='Required resume, transcript, or recommendation letter (PDF/DOC, max 5 MB).', upload_to=proposals.models.proposal_upload_path),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Cover letter / motivation for applying.'),
        ),
    ]
