# Generated by Django 6.0.3 on 2026-05-25 11:03

import proposals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_proposal_application_type_proposal_is_draft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(help_text='Roll number.', max_length=50)),
                ('name', models.CharField(help_text='Full name.', max_length=150)),
                ('dept', models.CharField(help_text='Department.', max_length=150)),
                ('phone_number', models.CharField(help_text='Phone number.', max_length=20)),
                ('email', models.EmailField(help_text='Email address.', max_length=254)),
                ('statement', models.CharField(help_text='Research Statement.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description.')),
                ('detailed_document', models.FileField(blank=True, help_text='Detailed specification document (PDF/DOC/ZIP, max 20 MB).', null=True, upload_to=proposals.models.own_statement_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Own Statement',
                'verbose_name_plural': 'Own Statements',
                'db_table': 'own_statements',
                'ordering': ['-created_at'],
            },
        ),
    ]
